FROM maven:3.9-eclipse-temurin-21 AS build
WORKDIR /app
# Copy the whole monorepo so Maven can see all declared modules
COPY . .
RUN mvn -pl cart-order -am -DskipTests package

FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /app/cart-order/target/cart-order-0.1.0-SNAPSHOT.jar app.jar
ENV JAVA_OPTS=""
EXPOSE 8083
ENTRYPOINT ["sh","-c","java $JAVA_OPTS -jar /app/app.jar"]
