server:
  port: 8087

spring:
  application:
    name: delivery-partner
  datasource:
    url: jdbc:h2:mem:deliverydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
